# Generated by Django 4.0.3 on 2022-04-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submitted',
            field=models.ImageField(upload_to=''),
        ),
    ]
