# Generated by Django 4.0.3 on 2022-03-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR', '0002_classroom_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='Teacher',
            new_name='teacher',
        ),
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
