# Generated by Django 4.0.3 on 2022-03-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR', '0003_rename_teacher_classroom_teacher_classroom_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
