# Generated by Django 4.0.3 on 2022-03-21 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OCR', '0005_classroom_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_desc', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=200)),
                ('marks', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='register_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OCR.classroom')),
                ('questions', models.ManyToManyField(to='OCR.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OCR.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OCR.student')),
            ],
        ),
    ]
