# Generated by Django 4.0.3 on 2022-03-21 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OCR', '0006_question_student_register_number_test_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='awarded_marks',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
