# Generated by Django 4.0.3 on 2022-03-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCR', '0007_answer_awarded_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='awarded_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
